# Generated by Django 4.1 on 2022-09-15 01:03

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('academy', models.CharField(max_length=254)),
                ('course', models.CharField(max_length=255)),
                ('recite', models.ImageField(upload_to='recite')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('FullName', models.CharField(max_length=100)),
                ('Profilepic', models.ImageField(default=users.models.get_default_profile_image, null=True, upload_to=users.models.get_profile_image_filepath)),
                ('Roll', models.CharField(default='user', max_length=50)),
                ('course', models.CharField(default='N/A', max_length=120)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('Academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='AcademicManager.academy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
