# Generated by Django 4.1 on 2022-09-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Academy',
            field=models.CharField(default='staff', max_length=200),
        ),
    ]
