# Generated by Django 4.1 on 2022-09-15 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcademicManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duriation', models.IntegerField()),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NewCourse', to='AcademicManager.academy')),
            ],
        ),
    ]
