# Generated by Django 4.1 on 2022-09-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICTDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TimeField()),
            ],
        ),
    ]
