# Generated by Django 4.1 on 2022-09-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicManager', '0002_ictdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ictdescription',
            name='name',
            field=models.CharField(default='ICT department', max_length=255),
            preserve_default=False,
        ),
    ]
