# Generated by Django 4.1 on 2022-09-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicManager', '0003_ictdescription_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictdescription',
            name='description',
            field=models.TextField(),
        ),
    ]
